const DEFAULT_PRODUCTS = [
    {
        id: 1,
        name: 'Áo thun basic nam nữ',
        category: 'ao',
        price: 1007000,
        description: 'Áo thun basic chất liệu cotton thoáng mát, dễ phối đồ',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 268,
        sold: 161,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 2,
        name: 'Quần jeans slimfit',
        category: 'quan',
        price: 4325000,
        description: 'Quần jeans slimfit chất liệu denim cao cấp, form ôm vừa vặn',
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 19,
        sold: 50,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 3,
        name: 'Giày thể thao Nike',
        category: 'giay',
        price: 4534000,
        description: 'Giày thể thao Nike chính hãng, êm ái và bền đẹp',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 111,
        sold: 224,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 4,
        name: 'Nón lưỡi trai thời trang',
        category: 'non',
        price: 224000,
        description: 'Nón lưỡi trai unisex, nhiều màu sắc, chất liệu vải cao cấp',
        image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 174,
        sold: 171,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 5,
        name: 'Áo sơ mi nam công sở',
        category: 'ao',
        price: 541000,
        description: 'Áo sơ mi nam form regular, chất liệu vải lụa mát mẻ',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 102,
        sold: 365,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 6,
        name: 'Quần short kaki',
        category: 'quan',
        price: 2691000,
        description: 'Quần short kaki nam nữ, chất liệu thấm hút tốt, thoáng mát',
        image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 108,
        sold: 135,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 7,
        name: 'Giày sandal nữ',
        category: 'giay',
        price: 794000,
        description: 'Giày sandal nữ quai ngang, đế bằng êm ái, nhiều màu sắc',
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 3,
        sold: 307,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 8,
        name: 'Nón rộng vành nữ',
        category: 'non',
        price: 914000,
        description: 'Nón rộng vành nữ đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        quantity: 473,
        sold: 43,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 9,
        name: 'Áo khoác nữ oversize',
        category: 'ao',
        price: 234000,
        description: 'Áo hoodie màu kem form rộng, có khóa kéo phía trước và dây rút ở mũ, tạo phong cách trẻ trung và thoải mái.',
        image: 'image/ao/ao3.png',
        quantity: 357,
        sold: 58,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 10,
        name: 'Áo khoác nam xành điệu',
        category: 'ao',
        price: 2133000,
        description: 'Áo khoác jean màu đen được treo trên móc, bên trong phối với áo thun trắng tạo phong cách đơn giản và hiện đại. Bên dưới có vài bộ quần áo được gấp gọn cùng một chậu cây trang trí, tạo cảm giác trưng bày như trong cửa hàng thời trang.',
        image: 'image/ao/ao2.png',
        quantity: 446,
        sold: 236,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 11,
        name: 'Nike Air Max Plus',
        category: 'giay',
        price: 4155000,
        description: 'Giày thể thao Nike Air Max Plus, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay1.png',
        quantity: 183,
        sold: 73,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 12,
        name: 'NikeCourt Slam',
        category: 'ao',
        price: 1809000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao5.png',
        quantity: 81,
        sold: 482,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    // Danh mục áo
    {
        id: 13,
        name: 'Áo thun đen',
        category: 'ao',
        price: 4152000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao6.png',
        quantity: 222,
        sold: 24,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 14,
        name: 'Áo thun đen tay dài',
        category: 'ao',
        price: 4289000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao7.png',
        quantity: 66,
        sold: 55,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 15,
        name: 'Nike-life',
        category: 'ao',
        price: 2084000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao8.png',
        quantity: 469,
        sold: 90,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 16,
        name: 'Nike sportswear',
        category: 'ao',
        price: 1632000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao9.png',
        quantity: 340,
        sold: 18,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 17,
        name: 'Nikecourt heritage',
        category: 'ao',
        price: 584000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao10.png',
        quantity: 265,
        sold: 13,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 18,
        name: 'Nike air',
        category: 'ao',
        price: 781000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao11.png',
        quantity: 247,
        sold: 188,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 19,
        name: 'Jordan Flight',
        category: 'ao',
        price: 900000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao12.png',
        quantity: 72,
        sold: 459,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 20,
        name: 'Áo Thun Training',
        category: 'ao',
        price: 2722000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao13.png',
        quantity: 80,
        sold: 69,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 21,
        name: 'Áo thun workout',
        category: 'ao',
        price: 1635000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao14.png',
        quantity: 300,
        sold: 56,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 22,
        name: 'Áo Polo ngắn tay',
        category: 'ao',
        price: 1724000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao15.png',
        quantity: 469,
        sold: 72,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 23,
        name: 'Nike Sportswear Tech',
        category: 'ao',
        price: 2225000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao16.png',
        quantity: 195,
        sold: 277,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 24,
        name: 'Áo Singlet All Time',
        category: 'ao',
        price: 4242000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao17.png',
        quantity: 64,
        sold: 184,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 24,
        name: 'Áo thun chest Stripes Engineered Collar',
        category: 'ao',
        price: 1887000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao18.png',
        quantity: 118,
        sold: 272,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 25,
        name: 'Áo dài tay adi365',
        category: 'ao',
        price: 3249000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao19.png',
        quantity: 134,
        sold: 412,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 26,
        name: 'Áo Thun Terrex Multi Meadow Pack',
        category: 'ao',
        price: 1478000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao20.png',
        quantity: 345,
        sold: 489,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 27,
        name: 'Áo Polo dài tay',
        category: 'ao',
        price: 4228000,
        description: 'Áo thể thao, rộng rãi, thoáng mát.',
        image: 'image/ao/ao21.png',
        quantity: 238,
        sold: 13,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 28,
        name: 'Nike Sportswear Club',
        category: 'quan',
        price: 325000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan1.png',
        quantity: 249,
        sold: 319,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 29,
        name: 'Standard Issue',
        category: 'quan',
        price: 3102000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan2.png',
        quantity: 480,
        sold: 305,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 30,
        name: 'Tartan',
        category: 'quan',
        price: 2144000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan3.png',
        quantity: 271,
        sold: 159,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 31,
        name: 'Form',
        category: 'quan',
        price: 1116000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan4.png',
        quantity: 38,
        sold: 193,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 32,
        name: 'Nike Club',
        category: 'quan',
        price: 3454000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan5.png',
        quantity: 195,
        sold: 246,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 33,
        name: 'Nike Pro Training',
        category: 'quan',
        price: 2862000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan6.png',
        quantity: 325,
        sold: 357,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 34,
        name: 'Kobe',
        category: 'quan',
        price: 4796000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan7.png',
        quantity: 66,
        sold: 65,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 35,
        name: 'Nike N.A.C.',
        category: 'quan',
        price: 2948000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan8.png',
        quantity: 168,
        sold: 362,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 36,
        name: 'Pro',
        category: 'quan',
        price: 1783000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan9.png',
        quantity: 68,
        sold: 3,
        gender: 'male',
        createdAt: new Date().toISOString()
    },
    {
        id: 37,
        name: 'Nike Pro Seamless',
        category: 'quan',
        price: 1298000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan10.png',
        quantity: 486,
        sold: 341,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 38,
        name: 'Nike One 7',
        category: 'quan',
        price: 1813000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan11.png',
        quantity: 390,
        sold: 246,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 39,
        name: 'One 89',
        category: 'quan',
        price: 4093000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan12.png',
        quantity: 468,
        sold: 247,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 40,
        name: 'Nike Swift',
        category: 'quan',
        price: 2191000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan13.png',
        quantity: 389,
        sold: 133,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 41,
        name: 'Nike Form',
        category: 'quan',
        price: 950000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan14.png',
        quantity: 33,
        sold: 444,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 42,
        name: 'Pro 365',
        category: 'quan',
        price: 3399000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan15.png',
        quantity: 316,
        sold: 63,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 43,
        name: 'Nike Sportswear 33',
        category: 'quan',
        price: 3193000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan16.png',
        quantity: 47,
        sold: 380,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 44,
        name: 'Nike Sportswear Chill Knit',
        category: 'quan',
        price: 2829000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan17.png',
        quantity: 82,
        sold: 170,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    {
        id: 45,
        name: 'Sportswear 15',
        category: 'quan',
        price: 2829000,
        description: 'Quần thể thao, rộng rãi, thoáng mát',
        image: 'image/quan/quan18.png',
        quantity: 82,
        sold: 170,
        gender: 'female',
        createdAt: new Date().toISOString()
    },
    //Danh mục nón
    {
        id: 46,
        name: 'Mũ Snapback in họa tiết Tour',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non1.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 47,
        name: 'Mũ Tour 3 gạch',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non2.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 48,
        name: 'Mũ lưỡi trai summer',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non3.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 49,
        name: 'Mũ nửa đầu tour',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non4.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 50,
        name: 'Mũ bucket',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non5.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 51,
        name: 'Mũ lưỡi trai Dynamic Cutlines',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non6.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 52,
        name: 'Mũ lưỡi trai Canvas 5 tấm',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non7.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 53,
        name: 'Mũ lưỡi trai Y-3 MERCEDES-AMG PETRONAS FORMULA 1 TEAM PODIUM',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non8.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 54,
        name: 'Mũ dad cap Y-3 MERCEDES-AMG PETRONAS FORMULA 1 TEAM PODIUM',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non9.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 55,
        name: 'Mũ DAD CAP GRAPHIC Y-3',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non10.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 56,
        name: 'Mũ Nửa Đầu Chóp Cao Golf Tour Originals',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non11.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 57,
        name: 'Mũ lưỡi trai MERCEDES - AMG PETRONAS FORMULA 1 TEAM DRIVER',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non12.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 58,
        name: 'Mũ Rộng Vành',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non13.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 59,
        name: 'Mũ lưỡi trai CHẠY BỘ 5 MẢNH CLIMACOOL',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non14.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 60,
        name: 'Mũ lưỡi trai MERCEDES - AMG PETRONAS FORMULA 1 TEAM DRIVER',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non15.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 61,
        name: 'Mũ Bucket',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non16.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 62,
        name: 'Mũ Bucket Terrex Xperior',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non17.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 63,
        name: 'Mũ lưỡi trai kẻ sọc Y-3',
        category: 'non',
        price: 2829000,
        description: 'Nón đi biển, chất liệu cói tự nhiên, nhẹ nhàng',
        image: 'image/non/non18.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    //Danh mục giày
    {
        id: 64,
        name: 'Nike Vaporfly 4',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Vaporfly 4, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay2.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 65,
        name: 'Nike Winflo 12',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Winflo 12, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay3.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 66,
        name: 'Nike Winflo 12',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Winflo 12, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay4.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 67,
        name: 'Nike Vapor Pro 3',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Vapor Pro 3, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay5.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 68,
        name: 'Nike ACG Izy SE',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike ACG Izy SE, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay6.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 69,
        name: 'Jordan Tiempo Streetgato SE',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Jordan Tiempo Streetgato SE, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay7.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 70,
        name: 'Nike ReactX Rejuven8',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike ReactX Rejuven8, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay8.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 71,
        name: 'Nike Pegasus Premium',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Pegasus Premium, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay9.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 72,
        name: 'Nike Vaporfly 4 Glam',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Vaporfly 4 Glam, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay10.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 73,
        name: 'LeBron Witness IX EP',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao LeBron Witness IX EP, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay11.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 74,
        name: 'Nike Flex Train',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Flex Train, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay12.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 75,
        name: 'Nike Run Defy',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Run Defy, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay13.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 76,
        name: 'Jordan Trunner O/S',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Jordan Trunner O/S, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay14.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 77,
        name: 'Jordan Session',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Jordan Session, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay15.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 78,
        name: 'Nike Air Max Dn8 Leather',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Air Max Dn8 Leather, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay16.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 79,
        name: 'Nike Air Max Portal',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Air Max Portal, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay17.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 80,
        name: 'Nike Pegasus Plus',
        category: 'giay',
        price: 2829000,
        description: 'Giày thể thao Nike Pegasus Plus, thiết kế hiện đại, êm ái và bền đẹp.',
        image: 'image/giay/giay18.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    //Danh mục phụ kiện
    {
        id: 81,
        name: 'Balo Chống Sốc',
        category: 'phukien',
        price: 2829000,
        description: 'Balo chống sốc, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien1.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 82,
        name: 'Balo Du Lịch Cao Cấp 38L',
        category: 'phukien',
        price: 2829000,
        description: 'Balo Du Lịch Cao Cấp 38L, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien2.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 83,
        name: 'Túi Du Lịch/ Gym Cao Cấp KINGBAG SKY',
        category: 'phukien',
        price: 2829000,
        description: 'Túi Du Lịch/ Gym Cao Cấp KINGBAG SKY, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien3.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 84,
        name: 'Balo Vintpack',
        category: 'phukien',
        price: 2829000,
        description: 'Balo Vintpack, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien4.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 85,
        name: 'Túi Đeo Chéo Thời Trang',
        category: 'phukien',
        price: 2829000,
        description: 'Túi Đeo Chéo Thời Trang, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien5.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 86,
        name: 'Kính râm TR855',
        category: 'phukien',
        price: 2829000,
        description: 'Kính râm TR855, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien6.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 87,
        name: 'Kính râm 2245',
        category: 'phukien',
        price: 2829000,
        description: 'Kính râm 2245, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien7.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 88,
        name: 'Kính râm 5188 C1 Gọng Ghi Mắt Đen',
        category: 'phukien',
        price: 2829000,
        description: 'Kính râm 5188 C1 Gọng Ghi Mắt Đen, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien8.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 89,
        name: 'Kính râm 28303 C1 Gọng Đen Mắt Đen',
        category: 'phukien',
        price: 2829000,
        description: 'Kính râm 28303 C1 Gọng Đen Mắt Đen, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien9.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 90,
        name: 'Kính râm 877 Gọng Xanh Mắt Nâu',
        category: 'phukien',
        price: 2829000,
        description: 'Kính râm 877 Gọng Xanh Mắt Nâu, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien10.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 91,
        name: 'Găng tay hở ngón',
        category: 'phukien',
        price: 2829000,
        description: 'Găng tay hở ngón, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien11.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 92,
        name: 'Găng Tay Lao Động',
        category: 'phukien',
        price: 2829000,
        description: 'Găng Tay Lao Động, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien12.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 93,
        name: 'Găng Tay Bảo Hộ',
        category: 'phukien',
        price: 2829000,
        description: 'Găng Tay Bảo Hộ, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien13.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 94,
        name: 'Găng Tay Đa Năng',
        category: 'phukien',
        price: 2829000,
        description: 'Găng Tay Đa Năng, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien14.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 95,
        name: 'Găng Tay Bảo Vệ Cổ Tay',
        category: 'phukien',
        price: 2829000,
        description: 'Găng Tay Bảo Vệ Cổ Tay, thiết kế hiện đại, bền đẹp.',
        image: 'image/phukien/phukien15.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 96,
        name: 'Mathey-Tissot Mathy I Day-Date H453ALN',
        category: 'phukien',
        price: 2829000,
        description: 'Mathey-Tissot Mathy I Day-Date H453ALN đẹp, sang chảnh, phụ hợp với mọi phong cách.',
        image: 'image/phukien/phukien16.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 97,
        name: 'Mathey-Tissot Mathy I Automatic H1450ATABU',
        category: 'phukien',
        price: 2829000,
        description: 'Mathey-Tissot Mathy I Automatic H1450ATABU đẹp, sang chảnh, phụ hợp với mọi phong cách.',
        image: 'image/phukien/phukien17.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 98,
        name: 'Mathey-Tissot Mathy Day-Date H510RS',
        category: 'phukien',
        price: 2829000,
        description: 'Mathey-Tissot Mathy Day-Date H510RS đẹp, sang chảnh, phụ hợp với mọi phong cách.',
        image: 'image/phukien/phukien18.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 99,
        name: 'Casio Edifice ECB-2300D',
        category: 'phukien',
        price: 2829000,
        description: 'Casio Edifice ECB-2300D đẹp, sang chảnh, phụ hợp với mọi phong cách.',
        image: 'image/phukien/phukien19.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    },
    {
        id: 100,
        name: 'Mathey-Tissot Mathy Chrono II H938CHAS',
        category: 'phukien',
        price: 2829000,
        description: 'Mathey-Tissot Mathy Chrono II H938CHAS đẹp, sang chảnh, phụ hợp với mọi phong cách.',
        image: 'image/phukien/phukien20.png',
        quantity: 82,
        sold: 170,
        gender: 'unisex',
        createdAt: new Date().toISOString()
    }
];

function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

DEFAULT_PRODUCTS.forEach(product => {
    product.id = getRandomInt(1, 100);
    product.price = getRandomInt(100, 5000) * 1000;
    product.quantity = getRandomInt(0, 500);
    product.sold = getRandomInt(0, 500);
});

function getDefaultProducts() {
    return DEFAULT_PRODUCTS.map(p => ({ ...p }));
}

// Sync data cho phép chỉnh thủ công trực tiếp trong item.js
// (Khi muốn sửa product chỉ cần edit DEFAULT_PRODUCTS, không cần vào admin)
const DEFAULT_PRODUCTS_VERSION = 1;
const CURRENT_PRODUCTS_VERSION = parseInt(localStorage.getItem('itemProductsVersion') || '0', 10);
if (CURRENT_PRODUCTS_VERSION !== DEFAULT_PRODUCTS_VERSION) {
    localStorage.setItem('products', JSON.stringify(DEFAULT_PRODUCTS));
    localStorage.setItem('itemProductsVersion', String(DEFAULT_PRODUCTS_VERSION));
}

